version: '3'
services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: izcss21/laravel:prod
    container_name: laravel
    networks:
      - laranet
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: izcss21/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge